namespace Albion.Common
{
    public enum HarvestableType
    {
        WOOD,
        WOOD_GIANTTREE,
        WOOD_CRITTER_GREEN,
        WOOD_CRITTER_RED,
        WOOD_CRITTER_DEAD,
        WOOD_GUARDIAN_RED,
        WOOD_MINIGUARDIAN_RED,
        ROCK,
        ROCK_CRITTER_GREEN,
        ROCK_CRITTER_RED,
        ROCK_CRITTER_DEAD,
        ROCK_GUARDIAN_RED,
        ROCK_MINIGUARDIAN_RED,
        FIBER,
        FIBER_CRITTER,
        FIBER_GUARDIAN_RED,
        FIBER_GUARDIAN_DEAD,
        FIBER_MINIGUARDIAN_RED,
        HIDE,
        HIDE_FOREST,
        HIDE_STEPPE,
        HIDE_SWAMP,
        HIDE_MOUNTAIN,
        HIDE_HIGHLAND,
        HIDE_CRITTER,
        HIDE_GUARDIAN,
        HIDE_MINIGUARDIAN,
        ORE,
        ORE_CRITTER_GREEN,
        ORE_CRITTER_RED,
        ORE_CRITTER_DEAD,
        ORE_GUARDIAN_RED,
        ORE_MINIGUARDIAN_RED
    }
}
